### ISSUE TITLE
codegen AssertionError: ts type for sol type undefined for balanceOfBatch not found (ERC1155)

### ISSUE THREAD

**Issue by zramsay** [cerc-io/watcher-ts#301]
from this config:

```
# Contracts to watch (required).
contracts:
    # Contract name.
  - name: ERC1155
    # Contract file path or an url.
    path: ../../node_modules/@openzeppelin/contracts/token/ERC1155/ERC1155.sol
    # Contract kind
    kind: Empty

# Output folder path (logs output using `stdout` if not provided).
outputFolder: ../test-erc1155-watcher

# Code generation mode [eth_call | storage | all | none] (default: none).
mode: all 

# Kind of watcher [lazy | active] (default: active).
kind: lazy

# Watcher server port (default: 3008).
host: 0.0.0.0
port: 3009

# Flatten the input contract file(s) [true | false] (default: true).
flatten: true
```

i get:

```
yarn codegen --config-file config.yaml 
yarn run v1.22.19
$ ts-node src/generate-code.ts --config-file config.yaml
AssertionError [ERR_ASSERTION]: ts type for sol type undefined for balanceOfBatch not found
    at Schema.addQuery (/root/watcher-ts/packages/codegen/src/schema.ts:40:11)
    at Visitor.functionDefinitionVisitor (/root/watcher-ts/packages/codegen/src/visitor.ts:70:20)
    at visit (/root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:118:25)
    at /root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:109:29
    at Array.forEach (<anonymous>)
    at visit (/root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:109:10)
    at visit (/root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:126:7)
    at /root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:109:29
    at Array.forEach (<anonymous>)
    at visit (/root/watcher-ts/node_modules/@solidity-parser/parser/src/parser.ts:109:10) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

if I change the config to `mode: eth_call` then same error, however, if `mode: storage` it works (by works I mean it creates the outputFolder with files, no additional testing was done)
